version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: DB_GERADOR_DE_SENHA
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: